### ISSUE TITLE
bib resources

### ISSUE THREAD

**Issue by wayne-wang-1119** [wayne-wang-1119/AdversarialCNN#3]
idk some readings if u r interested:
https://github.com/aaa123848/CNN_Candlestick
https://github.com/hardyqr/CNN-for-Stock-Market-Prediction-PyTorch
https://www.kaggle.com/datasets/farshidhossain68/candle-stick/data
https://arxiv.org/abs/1907.10046
https://github.com/ZacharyHimmelberger/image-classification-for-technical-indicators
https://arxiv.org/pdf/1901.05237.pdf

**Comment by wayne-wang-1119** [comment]
oops not all for bib mb

**Comment by wayne-wang-1119** [comment]
@jeevguha u mind add ur latest resources here? they look amazing

**Comment by jeevguha** [comment]
Hi Wayne,I’ll do it by the end of the weekend.JeevSent from my iPhoneOn Jan 26, 2024, at 11:55 AM, Wayne W. ***@***.***> wrote:﻿
@jeevguha u mind add ur latest resources here? they look amazing
